### ISSUE TITLE
Add the point generation

### ISSUE THREAD

**Issue by BearrXW** [Alpha-404/LangPRO#1]
🙏🙏

**Comment by Alpha-404** [comment]
Alright yeah I'll see what I can do but for now the homework completion adds points too

**Comment by BearrXW** [comment]
![image](https://github.com/Alpha-404/LangPRO/assets/80606070/ff2a9671-c827-4b17-baf2-b498e1dc9dd0)
This doesn't work that well but the 0 works

**Comment by Alpha-404** [comment]
Oh I should have clarified but the id is from newest hw to oldest, 0 being the newest 👍
